### ISSUE TITLE
BUG: Add server check back into preload scene

### ISSUE THREAD

**Issue by ccoyotedev** [machineman1357/spy-bri-pinball-api-template#1]
The game should check the server is running before starting the game. Currently people are getting frustrated that they are getting high scores and their scores arent being recorded due to the server being down.

https://github.com/machineman1357/spy-bri-pinball-api-template/blob/fa15e6a381184aaf5e1d4e4d5579171b9d973c00/src/game/scenes/boot-scene.ts#L114

**Comment by machineman1357** [comment]
Uncommented the line
