### ISSUE TITLE
BUG: Stuck in Plinko phase

### ISSUE THREAD

**Issue by ccoyotedev** [machineman1357/spy-bri-pinball-api-template#2]
Users often get stuck in the Plinko phase with no balls left. According to the console, 1 ball remains.

**Comment by machineman1357** [comment]
I am failing to recreate the bug.
Any additional information will help, ex.: does it happen after the last ball enters the red ring? Does it happen after all balls don't hit any tubes?
But to solve this, I will add a periodic check to see if any balls are above a certain distance, and if not, then I'm assuming all balls are completed (but the physics bugged out) and will return to pinbal scene.

**Comment by machineman1357** [comment]
I added the above fix.
